import { userdto } from 'src/users/dto/user.dto';

export const useData: userdto[] = [
  {
    id: 1,
    first_name: 'Rudie',
    last_name: 'Hartness',
    email: 'rhartness0@amazon.de',
    gender: 'Male',
  },
  {
    id: 2,
    first_name: 'Anissa',
    last_name: 'Dusting',
    email: 'adusting1@ftc.gov',
    gender: 'Female',
  },
  {
    id: 3,
    first_name: 'Nicolis',
    last_name: 'Mew',
    email: 'nmew2@hc360.com',
    gender: 'Male',
  },
  {
    id: 4,
    first_name: 'Norbert',
    last_name: 'Licence',
    email: 'nlicence3@reverbnation.com',
    gender: 'Male',
  },
  {
    id: 5,
    first_name: 'Joyann',
    last_name: 'Klimschak',
    email: 'jklimschak4@aol.com',
    gender: 'Female',
  },
  {
    id: 6,
    first_name: 'Evelin',
    last_name: 'Bartalin',
    email: 'ebartalin5@chicagotribune.com',
    gender: 'Male',
  },
  {
    id: 7,
    first_name: 'Yvon',
    last_name: 'Kears',
    email: 'ykears6@dot.gov',
    gender: 'Male',
  },
  {
    id: 8,
    first_name: 'Annamarie',
    last_name: 'Josskoviz',
    email: 'ajosskoviz7@cbslocal.com',
    gender: 'Female',
  },
  {
    id: 9,
    first_name: 'Melany',
    last_name: 'Buten',
    email: 'mbuten8@oakley.com',
    gender: 'Female',
  },
  {
    id: 10,
    first_name: 'Harlen',
    last_name: 'Bucknill',
    email: 'hbucknill9@bluehost.com',
    gender: 'Male',
  },
  {
    id: 11,
    first_name: 'Ranique',
    last_name: 'Frodsam',
    email: 'rfrodsama@hud.gov',
    gender: 'Female',
  },
  {
    id: 12,
    first_name: 'Mattie',
    last_name: 'Attryde',
    email: 'mattrydeb@studiopress.com',
    gender: 'Male',
  },
  {
    id: 13,
    first_name: 'Doreen',
    last_name: 'Ellick',
    email: 'dellickc@usda.gov',
    gender: 'Female',
  },
  {
    id: 14,
    first_name: 'Gregorius',
    last_name: 'Norledge',
    email: 'gnorledged@toplist.cz',
    gender: 'Male',
  },
  {
    id: 15,
    first_name: 'Noell',
    last_name: 'Whillock',
    email: 'nwhillocke@phoca.cz',
    gender: 'Bigender',
  },
  {
    id: 16,
    first_name: 'Aubrey',
    last_name: 'Scarrisbrick',
    email: 'ascarrisbrickf@acquirethisname.com',
    gender: 'Female',
  },
  {
    id: 17,
    first_name: 'Nathanil',
    last_name: 'Drinkhall',
    email: 'ndrinkhallg@unicef.org',
    gender: 'Male',
  },
  {
    id: 18,
    first_name: 'Hugo',
    last_name: 'Horick',
    email: 'hhorickh@fotki.com',
    gender: 'Male',
  },
  {
    id: 19,
    first_name: 'Odessa',
    last_name: 'Jeroch',
    email: 'ojerochi@accuweather.com',
    gender: 'Female',
  },
  {
    id: 20,
    first_name: 'Abbe',
    last_name: 'Kiebes',
    email: 'akiebesj@ox.ac.uk',
    gender: 'Male',
  },
];
